In [2]:
import torch

x = torch.arange(13)
print(x[::3])

tensor([ 0,  3,  6,  9, 12])


In [99]:
x = torch.tensor([1.0, 2.0, 3.0])  # 3 elements
y = torch.tensor([1.1, 2.1, 3.1, 4.1])  # 4 elements
print(x)
print(y)

tensor([1., 2., 3.])
tensor([1.1000, 2.1000, 3.1000, 4.1000])


In [100]:
count = 0
for xi in x:
    for yi in y:
        if abs(xi - yi) < 1e-3:
            count += 1
            break
torch.as_tensor(count)

tensor(0)

In [80]:
torch.diff(torch.cat((x,y)))

tensor([-1.3320, -0.2045, -0.4514,  1.6307,  0.0000,  0.0000])

In [111]:
diff = torch.abs(x.unsqueeze(1) - y.unsqueeze(0))
matches = diff < 1e-3
torch.any(matches, dim=1)
# torch.sum(torch.any(matches, dim=1))

tensor([False, False, False, False])

In [110]:
x.unsqueeze(0).shape

torch.Size([1, 3])