In [13]:
import numpy as np
from pathlib import Path

dataset_path = Path("./drive_data/train/cornfield_crossing_00")

info = np.load(dataset_path/'info.npz', allow_pickle=True)

In [14]:
info.files

['track', 'frames']

In [15]:
for key in info.files:
    print(f"{key}: {info[key].shape}")

track: ()
frames: ()


In [18]:
print("track contents:", info['track'])
print("\nframes contents:", info['frames'])

track contents: {'path_nodes': array([[[ 0.40949988,  0.355     , 18.822     ],
        [ 0.40949988,  0.355     , 24.698     ]],

       [[ 0.40949988,  0.355     , 24.698     ],
        [ 0.40949988,  0.355     , 30.573     ]],

       [[ 0.40949988,  0.355     , 30.573     ],
        [ 0.40949988,  0.355     , 61.649     ]],

       ...,

       [[ 0.40949988,  0.355     ,  7.071     ],
        [ 0.40949988,  0.355     , 12.947     ]],

       [[ 0.40949988,  0.355     , 12.947     ],
        [ 0.40949988,  0.355     , 18.17      ]],

       [[ 0.40949988,  0.355     , 18.17      ],
        [ 0.40949988,  0.355     , 18.822     ]]], dtype=float32), 'path_distance': array([[   0.       ,    5.8759995],
       [   5.8759995,   11.750999 ],
       [  11.750999 ,   42.826996 ],
       [  42.826996 ,   52.634705 ],
       [  52.634705 ,   57.86182  ],
       [  57.86182  ,   60.793526 ],
       [  60.793526 ,   63.63824  ],
       [  63.63824  ,   66.37862  ],
       [  66.37862  ,   68.

In [19]:
print("=== TRACK CONTENTS ===")
track_dict = info['track'].item()
for key in track_dict:
    print(f"\nKey: {key}")
    print(f"Type: {type(track_dict[key])}")
    print(f"Shape: {track_dict[key].shape}")
    print(f"Sample data:\n{track_dict[key][:2]}")

=== TRACK CONTENTS ===

Key: path_nodes
Type: <class 'numpy.ndarray'>
Shape: (273, 2, 3)
Sample data:
[[[ 0.40949988  0.355      18.822     ]
  [ 0.40949988  0.355      24.698     ]]

 [[ 0.40949988  0.355      24.698     ]
  [ 0.40949988  0.355      30.573     ]]]

Key: path_distance
Type: <class 'numpy.ndarray'>
Shape: (273, 2)
Sample data:
[[ 0.         5.8759995]
 [ 5.8759995 11.750999 ]]

Key: path_width
Type: <class 'numpy.ndarray'>
Shape: (273, 1)
Sample data:
[[10.857]
 [10.857]]


In [21]:
print("\n=== FRAMES CONTENTS ===")
frames_dict = info['frames'].item()
for key in frames_dict:
    print(f"\nKey: {key}")
    print(f"Type: {type(frames_dict[key])}")
    if isinstance(frames_dict[key], list):
        print(f"Length: {len(frames_dict[key])}")
        print(f"Sample data shape: {np.array(frames_dict[key][0]).shape}")  # Convert to np.array to get shape
        print(f"Sample data:\n{frames_dict[key][0]}")


=== FRAMES CONTENTS ===

Key: V
Type: <class 'list'>
Length: 500
Sample data shape: (4, 4)
Sample data:
[[ 9.99999940e-01 -3.97743890e-04  1.03773535e-04  0.00000000e+00]
 [ 4.09678323e-04  9.85030651e-01 -1.72378868e-01  0.00000000e+00]
 [-3.36574703e-05  1.72378898e-01  9.85030711e-01  0.00000000e+00]
 [ 8.92707348e-01 -3.06269693e+00 -1.42534437e+01  1.00000000e+00]]

Key: P
Type: <class 'list'>
Length: 500
Sample data shape: (4, 4)
Sample data:
[[ 0.8938152  0.         0.         0.       ]
 [ 0.         1.1917536  0.         0.       ]
 [ 0.         0.         1.001001   1.       ]
 [ 0.         0.        -1.001001   0.       ]]

Key: location
Type: <class 'list'>
Length: 500
Sample data shape: (3,)
Sample data:
[-0.8919347  -0.29050708 16.568068  ]

Key: front
Type: <class 'list'>
Length: 500
Sample data shape: (3,)
Sample data:
[-0.8919347  -0.29050708 17.286568  ]

Key: velocity
Type: <class 'list'>
Length: 500
Sample data shape: (3,)
Sample data:
[1.09691899e-02 8.17238688e-0

In [25]:
frames_dict = info['frames'].item()
frames_dict['front']

[array([-0.8919347 , -0.29050708, 17.286568  ], dtype=float32),
 array([-0.791435  , -0.29756385, 17.964472  ], dtype=float32),
 array([-0.6446513 , -0.30098853, 19.584314  ], dtype=float32),
 array([-0.46756676, -0.3026913 , 21.59856   ], dtype=float32),
 array([-0.3961588 , -0.30208892, 23.787205  ], dtype=float32),
 array([-0.32457483, -0.30261686, 26.04897   ], dtype=float32),
 array([-0.25248462, -0.30268255, 28.343006  ], dtype=float32),
 array([-0.18123841, -0.30263236, 30.637531  ], dtype=float32),
 array([-0.11084609, -0.30257928, 32.932076  ], dtype=float32),
 array([-0.04129921, -0.30252752, 35.226627  ], dtype=float32),
 array([ 2.7108923e-02, -3.0247661e-01,  3.7521248e+01], dtype=float32),
 array([ 0.0904473, -0.3024262, 39.81591  ], dtype=float32),
 array([ 0.14807604, -0.30238277, 42.11078   ], dtype=float32),
 array([ 0.20024449, -0.30234623, 44.40577   ], dtype=float32),
 array([ 0.24940164, -0.3023216 , 46.700832  ], dtype=float32),
 array([ 0.29537374, -0.30229884, 

In [26]:
''' RAW DATA SUMMARY:
1. 500 depth img of the car on the track, represents the distance
2. 500 actual img of the car on the track, represents the actual scene
3. info.npz, contains track and frames, where:
    a. track:
        . path_nodes : (273, 2, 3), represents the lines in 3D space of the track
        . path_distance: (273, 2), represents the distance from start to end
        . path_width: (273, ), represents the width of the track
    b. frames: captures the trajectory of the car in 500 frames
        . V: (500, 4, 4), represents the camera view
        . P: (500, 4, 4), represents how far the camera is
        . location: (500, 3), coordinate of the car in a particular frame
        . front: (500, 3), 3D vector represents which direction the car is facing
'''

'\n1. 500 depth img of the car on the track, represents the distance\n2. 500 actual img of the car on the track, represents the actual scene\n3. info.npz, contains track and frames, where:\n    a. track:\n        . path_nodes : (273, 2, 3), represents the lines in 3D space of the track\n        . path_distance: (273, 2), represents the distance from start to end\n        . path_width: (273, ), represents the width of the track\n    b. frames: captures the trajectory of the car in 500 frames\n        . V: (500, 4, 4), represents the camera view\n        . P: (500, 4, 4), represents how far the camera is\n        . location: (500, 3), coordinate of the car in a particular frame\n        . front: (500, 3), 3D vector represents where the car is heading\n'

In [ ]:
''' AFTER TRANSFORM:
1. track_left: (10, 2): 10 points in 2D marking left boundary
2. track_right: (10, 2): 10 points in 2D marking the right boundary
3. way_points: (3, 2): 3 points in 2D represents where the car is heading
4. waypoints_mask: (3,): Boolean mask for valid waypoints
5. image: (3, H, W): 
'''

''' way_points visualization


   z (forward)
   ↑    
   |    • location[103] (3rd waypoint)
   |    
   |    • location[102] (2nd waypoint)
   |    
   |    • location[101] (1st waypoint)
   |    
   🚗→ location[100] (current position)
    ↑  front[100] (direction car faces)
   +——— x (left/right)

'''